Converted to typescript.
josh-umahi/wordbanker pull request #3
Opened 2022-07-29 19:09 UTC by NG-Joseph

@josh-umahi Awaiting your review! There were some JS logic bugs uncovered by TS, which I probably flagged with `TODO:` or `@ts-ignore`.  For example, `api.likePost()` takes 1 arg, but two are passed in `post.ts`.

Cheers!

2022-07-30 04:20 UTC, josh-umahi requested changes
Will finish reviewing the remaining 4 later

2022-07-30 04:20 UTC, josh-umahi commented on client/src/utils/formatDate.ts
> +const toOrdinalSuffix = (numb: number | string) => {
I think the next step in the Typescript transformation would be to specify a return type for most of the Typescript functions. no pressure, let me know what you think

2022-07-30 04:20 UTC, josh-umahi commented on client/src/routes/Home/Home.tsx
> +    const scrollToBrowseWords = () => scroll.scrollTo(refToBrowseWords.current!.offsetTop - 20);
This would most likely cause an error on first run of the component because refToBrowseWords starts out being null

2022-07-30 04:20 UTC, josh-umahi commented on client/src/routes/Auth/Input.tsx
> +      } : undefined}
To return nothing in a React component I would prefer to return null than undefined. I'm not too [finicky](https://wordbanker.vercel.app/posts/62c9d539d8db66f1467ccde1) about it but if you have a reason for preferring undefined let me know.

2022-07-30 04:20 UTC, josh-umahi commented on client/src/routes/Auth/Auth.tsx
> +//const handleChange = (e: React.FormEvent<EventTarget>)
Clear unused comments when committing (expect they are TODOs or of importance)

2022-07-30 04:20 UTC, josh-umahi commented on client/src/App.tsx
> +  // This is because React Router V6+ doesn't support it anymore.
Thanks a lot bro!, didn't know this

2022-07-30 04:20 UTC, josh-umahi commented on client/src/context/AppContext.tsx
> +// Using so we can access the children prop without any TS complaints
that's neat, I'm learning some shit yo!

2022-07-30 04:20 UTC, josh-umahi commented on client/src/routes/Home/styles.ts
> +        //TODO: Add this as something in @Home.tsx depends on it
Sorry I forgot I deleted the styles for outer, it's no longer needed so I suggest you delete it from here and also delete its usage in the Home.tsx

2022-07-30 04:20 UTC, josh-umahi commented on client/src/components/WordOfTheDay/WordOfTheDay.tsx
> +    // TODO: This is a hack. Refactor typings.
I'll add it to my agenda, might take a while to get to it though because of Finals

2022-07-30 08:52 UTC, NG-Joseph commented on client/src/routes/Home/Home.tsx
> +    const scrollToBrowseWords = () => scroll.scrollTo(refToBrowseWords.current!.offsetTop - 20);
Oh fr. I thought using useRef() assumes a null value anyway

2022-08-14 13:31 UTC, josh-umahi approved these changes

2022-08-14 13:35 UTC, josh-umahi approved these changes

2022-08-14 13:42 UTC, josh-umahi commented on client/src/routes/Home/Home.tsx
> +    const scrollToBrowseWords = () => scroll.scrollTo(refToBrowseWords.current!.offsetTop - 20);
My bad sorry I forgot scrollToBrowseWords is a function

2022-08-15 00:43 UTC, josh-umahi approved these changes

2022-08-15 06:44 UTC, merged